### ISSUE TITLE
文件上传接收json格式返回数据 默认的okhttp3可以接收并解析，httpclient接收的数据为content中的数据。

### ISSUE THREAD

**Issue by jtc1998** [mySingleLive/forest#11]
1. 在使用文件上传的时候发现指定了backend：httpclient时，文件上传接口返还的json数据为 forestResponse中的content内容，而forestResponse中result没有数据导致json解析失败。

2. 默认的okhttp3来实现上传请求没有问题。

**Comment by mySingleLive** [comment]
请问是什么版本

**Comment by jtc1998** [comment]
你好，微信已和您联系过，在1.4.0-CR3中已解决。
我的微信号：steven104640


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mySingleLive/forest"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午3:17
收件人:&nbsp;"mySingleLive/forest"<forest@noreply.github.com&gt;;
抄送:&nbsp;"贾铁城-17376592886-249044756@qq.com"<249044756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mySingleLive/forest] 文件上传接收json格式返回数据 默认的okhttp3可以接收并解析，httpclient接收的数据为content中的数据。 (#11)





 
请问是什么版本
